---
title: <font size="6"> About Us</font> 
author: 
output:
  html_document:
    theme: flatly
    highlight: pygments
    number_sections: false
    self_contained: true
    lib_dir: libs
    fig_caption: true
    toc: false
    toc_float: false

---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE)
```

We are a group of Master's students in the Krannert School of Management at Purdue University studying Business Analytics and Information Management.

* Kai-Duan Chang
* Li-Ci Chuang
* Sri Manogna Gurijala
* Ryan Egbert
* Meghan Harris

## About the Project

Many high school students run into a dilemma upon graduation. They don't know where to even begin when trying to select a college major.
And it is not just graduating high school students; according to the National Center for Education Studies, 30% of college students in 
undergraduate programs had changed their major at least once and 10% of undergraduate students changed their major two or more times.

In order to help these student make better, well informed decisions, our group has set out to create a tool to aid in this decision making
process.

## Code

Our code was written in R using Shiny. See the 'Documentation' tab for more information on the app.

The code for this project can be found on [GitHub](https://github.com/ryan-egbert/shiny_app_r)
